my_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "localhost"
      port: 5432  # Ensure this is a string
      user: "zelalemtegene"
      password: "112233"
      dbname: "my_database"
      schema: "public"